# Lecture 15

### Indexing, selection and filtering
* Series and DataFrame can be sliced/accessed with label-based indexes, or using position-based indexes similar to Numpy Array

In [87]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np
from numpy import nan as NaN

In [88]:
S = Series(range(4), index=['zero', 'one', 'two', 'three'])
print(S['two'],"\n")
print(S[2],"\n") #same as above

print(S[['zero', 'two']],"\n")
print(S[[0,2]],"\n")#same as above

print(S[:2],"\n")
print(S['zero':'two'],"\n")#unlike above code, inclusive of index 2

print(S[S > 1],"\n")#returns elements greater than 1
print(S[-2:],"\n")#returns last two indices

2 

2 

zero    0
two     2
dtype: int64 

zero    0
two     2
dtype: int64 

zero    0
one     1
dtype: int64 

zero    0
one     1
two     2
dtype: int64 

two      2
three    3
dtype: int64 

two      2
three    3
dtype: int64 



### datatrame– retrieving a column
* A column in a DataFrame can be retrieved as a Series by dict-like notation or as attribute
* Series index and name have been kept/set appropriately


In [89]:
data= {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
       'year': [2000, 2001, 2002, 2001, 2002],
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)
print(frame,"\n")

print(frame['state'],"\n")#prints state key
print(frame.state,"\n") #same as above

print(type(frame['state']))

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9 

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
Name: state, dtype: object 

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
Name: state, dtype: object 

<class 'pandas.core.series.Series'>


#### dataframe– getting rows
* loc for using labels and iloc for using positions

In [90]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame2 = DataFrame(data,
                   columns=['year', 'state', 'pop', 'debt'], #columns can be renamed, in same order written
                   index=['A', 'B', 'C', 'D', 'E']) #assigning labels of each row
print(frame2,"\n")

print(frame2.loc['A'],"\n") #returns row A data
print(type(frame2.loc['A']),"\n")

print(frame2.loc[['A', 'B']],"\n")#returns dataframe of A&B data
print(type(frame2.loc[['A', 'B']]),"\n")

print(frame2.iloc[0],"\n") #returns location of index zero
print( frame2.iloc[[0, 1]])#returns location of index zero&one

   year   state  pop debt
A  2000    Ohio  1.5  NaN
B  2001    Ohio  1.7  NaN
C  2002    Ohio  3.6  NaN
D  2001  Nevada  2.4  NaN
E  2002  Nevada  2.9  NaN 

year     2000
state    Ohio
pop       1.5
debt      NaN
Name: A, dtype: object 

<class 'pandas.core.series.Series'> 

   year state  pop debt
A  2000  Ohio  1.5  NaN
B  2001  Ohio  1.7  NaN 

<class 'pandas.core.frame.DataFrame'> 

year     2000
state    Ohio
pop       1.5
debt      NaN
Name: A, dtype: object 

   year state  pop debt
A  2000  Ohio  1.5  NaN
B  2001  Ohio  1.7  NaN


### dataframe– modifying columns

In [91]:
frame2['debt'] = 0 #set all data values to zero
print(frame2,"\n")

frame2['debt'] = range(5) #set data values in range of 5
print(frame2,"\n")

val = Series([10, 10, 10], #assigning specific rows the value 10
             index = ['A', 'C', 'D']) #it doesn't appear in data frame unless assigned to a specific column
#frame2['debt'] = val #assigning those values to the debt column
print(frame2,"\n")

   year   state  pop  debt
A  2000    Ohio  1.5     0
B  2001    Ohio  1.7     0
C  2002    Ohio  3.6     0
D  2001  Nevada  2.4     0
E  2002  Nevada  2.9     0 

   year   state  pop  debt
A  2000    Ohio  1.5     0
B  2001    Ohio  1.7     1
C  2002    Ohio  3.6     2
D  2001  Nevada  2.4     3
E  2002  Nevada  2.9     4 

   year   state  pop  debt
A  2000    Ohio  1.5     0
B  2001    Ohio  1.7     1
C  2002    Ohio  3.6     2
D  2001  Nevada  2.4     3
E  2002  Nevada  2.9     4 



### dataframe– modifying rows
* Rows or individual elements can be modified similarly using loc or iloc

In [92]:
frame2 = DataFrame(data,
                   columns=['year', 'state', 'pop', 'debt'], #columns can be renamed, in same order written
                   index=['A', 'B', 'C', 'D', 'E'])

frame2.loc['A'] = Series([2000, 'PA', 1.1],
                         index=['year', 'state', 'pop'])
print(frame2,"\n")


frame2.iloc[1] =  Series([2005, 'MA', 1.1,NaN],
                         index=['year', 'state', 'pop','debt'])
print(frame2,"\n")

   year   state  pop debt
A  2000      PA  1.1  NaN
B  2001    Ohio  1.7  NaN
C  2002    Ohio  3.6  NaN
D  2001  Nevada  2.4  NaN
E  2002  Nevada  2.9  NaN 

   year   state  pop debt
A  2000      PA  1.1  NaN
B  2005      MA  1.1  NaN
C  2002    Ohio  3.6  NaN
D  2001  Nevada  2.4  NaN
E  2002  Nevada  2.9  NaN 



### More on DataFrame indexing

In [93]:
data = np.arange(9).reshape(3,-1)#9 values divided into 3 rows
print(data)

frame = DataFrame(data,
                  index=['r1', 'r2', 'r3'],
                  columns=['c1', 'c2', 'c3'])
print(frame,"\n")
print(frame['c1'],"\n")
print(frame.loc['r1'],"\n")
print(frame['c1']['r1'],"\n")
print(frame[['c1', 'c3']],"\n")
print(frame.loc[['r1','r3']],"\n")
#Row slices
print(frame.iloc[:2],"\n")
print(frame[:2],"\n")
print(frame.loc[['r1', 'r2'], ['c1', 'c2']],"\n")
print(frame.loc['r1':'r3', 'c1':'c3'],"\n")
print(frame.iloc[:2,:2],"\n")



[[0 1 2]
 [3 4 5]
 [6 7 8]]
    c1  c2  c3
r1   0   1   2
r2   3   4   5
r3   6   7   8 

r1    0
r2    3
r3    6
Name: c1, dtype: int32 

c1    0
c2    1
c3    2
Name: r1, dtype: int32 

0 

    c1  c3
r1   0   2
r2   3   5
r3   6   8 

    c1  c2  c3
r1   0   1   2
r3   6   7   8 

    c1  c2  c3
r1   0   1   2
r2   3   4   5 

    c1  c2  c3
r1   0   1   2
r2   3   4   5 

    c1  c2
r1   0   1
r2   3   4 

    c1  c2  c3
r1   0   1   2
r2   3   4   5
r3   6   7   8 

    c1  c2
r1   0   1
r2   3   4 



In [94]:
v = DataFrame(np.arange(9).reshape(3,3),
              index=['a', 'a', 'b'],
              columns=['c1','c2','c3'])
print(v,"\n")
print(v.loc['a'],"\n")


   c1  c2  c3
a   0   1   2
a   3   4   5
b   6   7   8 

   c1  c2  c3
a   0   1   2
a   3   4   5 



In [95]:

print(frame,"\n")
print(frame[frame['c1']>0],"\n")
print(frame['c1']>0,"\n")
print(frame < 3,"\n")
frame[frame<3] = 3
print(frame,"\n")

    c1  c2  c3
r1   0   1   2
r2   3   4   5
r3   6   7   8 

    c1  c2  c3
r2   3   4   5
r3   6   7   8 

r1    False
r2     True
r3     True
Name: c1, dtype: bool 

       c1     c2     c3
r1   True   True   True
r2  False  False  False
r3  False  False  False 

    c1  c2  c3
r1   3   3   3
r2   3   4   5
r3   6   7   8 



### DataFrame– removing columns

In [96]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame2 = DataFrame(data,
                   columns=['year', 'state', 'pop', 'debt'], #columns can be renamed, in same order written
                   index=['A', 'B', 'C', 'D', 'E'])
print(frame2,"\n")
del frame2['debt']
print(frame2)

   year   state  pop debt
A  2000    Ohio  1.5  NaN
B  2001    Ohio  1.7  NaN
C  2002    Ohio  3.6  NaN
D  2001  Nevada  2.4  NaN
E  2002  Nevada  2.9  NaN 

   year   state  pop
A  2000    Ohio  1.5
B  2001    Ohio  1.7
C  2002    Ohio  3.6
D  2001  Nevada  2.4
E  2002  Nevada  2.9


### Removing rows/columns

In [97]:
data = np.arange(9).reshape(3,-1)#9 values divided into 3 rows

frame = DataFrame(data,
                  index=['r1', 'r2', 'r3'],
                  columns=['c1', 'c2', 'c3'])
print(frame,"\n")
#del=error
#del frame.loc['c1'] -> AttributeError: __delitem__
#del frame.loc[‘r1’] -> AttributeError: __delitem__

print(frame.drop('r1'),"\n")
print(frame.drop(['r1','r3']),"\n")
print(frame.drop(['c1'], axis=1),"\n")

    c1  c2  c3
r1   0   1   2
r2   3   4   5
r3   6   7   8 

    c1  c2  c3
r2   3   4   5
r3   6   7   8 

    c1  c2  c3
r2   3   4   5 

    c2  c3
r1   1   2
r2   4   5
r3   7   8 



### Reindexing
* Alter the order of rows/columns of a DataFrame or order of a series according to new index

In [98]:
print(frame,"\n")
print(frame.reindex(['r1', 'r3', 'r2', 'r4']),"\n") #adds extra row
print(frame.reindex(columns=['c2', 'c3', 'c1'])) #reorders columns

    c1  c2  c3
r1   0   1   2
r2   3   4   5
r3   6   7   8 

     c1   c2   c3
r1  0.0  1.0  2.0
r3  6.0  7.0  8.0
r2  3.0  4.0  5.0
r4  NaN  NaN  NaN 

    c2  c3  c1
r1   1   2   0
r2   4   5   3
r3   7   8   6


### Function application and mapping
* DataFrame.applymap(f) applies f to every entry
* DataFrame.apply(f) applies f to every column (default) or row

In [99]:
print(frame,"\n")

#applies square to every entry
def square(x): return x**2
print(frame.applymap(square),"\n")

#returns every column's max value minus min value
def max_minus_min(x): return max(x)-min(x)
print(frame.apply(max_minus_min),"\n")
print(frame.apply(max_minus_min, axis=1),"\n") #same as above except with the rows

#returns a series that updates the frame with the max values of each column in row1 and the min of each column in row2
def max_min(x): return Series([max(x), min(x)], index=['max', 'min'])
print(frame.apply(max_min))

    c1  c2  c3
r1   0   1   2
r2   3   4   5
r3   6   7   8 

    c1  c2  c3
r1   0   1   4
r2   9  16  25
r3  36  49  64 

c1    6
c2    6
c3    6
dtype: int64 

r1    2
r2    2
r3    2
dtype: int64 

     c1  c2  c3
max   6   7   8
min   0   1   2


### Other DataFrame functions
* sort_index()
* sort_values()
* Rank()

In [100]:
frame.index=['A', 'C', 'B']
frame.columns=['b','a','c']

#sort_index()
print(frame.sort_index(),"\n")
print(frame.sort_index(axis=1),"\n") #sorts frame according to the columns

#sort_values()
frame = DataFrame(np.random.randint(0, 10, 9).reshape(3,-1),
                    index=['r1', 'r2', 'r3'],
                    columns=['c1', 'c2', 'c3'])
print(frame,"\n")
print(frame.sort_values(by='c1'),"\n") #sorts values in column c1
print(frame.sort_values(axis=1, by=['r3','r1']),"\n") #sorts columns by values in r3 and r1, lowest to highest

#Rank()
print(frame,"\n")
print(frame.rank(axis=1)) #ranks the different elements in place, 1.5 if they tie

   b  a  c
A  0  1  2
B  6  7  8
C  3  4  5 

   a  b  c
A  1  0  2
C  4  3  5
B  7  6  8 

    c1  c2  c3
r1   9   8   3
r2   4   4   3
r3   2   4   3 

    c1  c2  c3
r3   2   4   3
r2   4   4   3
r1   9   8   3 

    c1  c3  c2
r1   9   3   8
r2   4   3   4
r3   2   3   4 

    c1  c2  c3
r1   9   8   3
r2   4   4   3
r3   2   4   3 

     c1   c2   c3
r1  3.0  2.0  1.0
r2  2.5  2.5  1.0
r3  1.0  3.0  2.0


### Other DataFrame functions
* mean()
* Mean(axis=0, skipna=True) 
* sum() 
* cumsum() 
* describe(): return summary statistics of each column 
* for numeric data: mean, std, max, min, 25%, 50%, 75%, etc. 
* For non-numeric data: count, uniq, most-frequent item, etc. 
* corr(): correlation between two Series, or between columns of a DataFrame 
* corr_with(): correlation between columns of DataFram and a series or between the columns of another DataFrame

### Handling missing data
* Filtering out missing values

In [101]:
data = Series([1, NaN, 2.5, NaN, 6])
print(data.dropna())

0    1.0
2    2.5
4    6.0
dtype: float64
